image: gitpod/workspace-postgres

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: npm i # runs during prebuild
    init: npm run setup
    command: npm start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
  - port: 5432
    onOpen: ignore
